/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class log_NetLog */

#ifndef _Included_log_NetLog
#define _Included_log_NetLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     log_NetLog
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_log_NetLog_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     log_NetLog
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_log_NetLog_uninit
  (JNIEnv *, jobject);

/*
 * Class:     log_NetLog
 * Method:    logInfo
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_log_NetLog_logInfo
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
